on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      release_notes:
        required: true
        type: string
      build_task:
        required: true
        type: string
      artifact_path:
        required: true
        type: string
    secrets:
      google-services-json:
        required: true
      keystore-base64:
        required: true
      keystore-password:
        required: true
      key-alias:
        required: true
      firebase-credential-file-content:
        required: true
      firebase-app-id:
        required: true

name: build-and-distribute

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_tag }}
      - name: Create google-services.json
        run: echo '${{ secrets.google-services-json }}' > ./composeApp/google-services.json
      - name: Decode and setup keystore
        run: |
          echo "${{ secrets.keystore-base64 }}" | base64 -d > ${{ github.workspace }}/spacex-release-keystore.jks
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.14.3'
      - name: Build Android App
        env:
          RELEASE_KEYSTORE_FILE: ${{ github.workspace }}/spacex-release-keystore.jks
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.keystore-password }}
          RELEASE_KEY_ALIAS: ${{ secrets.key-alias }}
          RELEASE_KEY_PASSWORD: ${{ secrets.keystore-password }}
        run: gradle ${{ inputs.build_task }}
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.release_tag }} ${{ inputs.artifact_path }}
      - name: Create release notes file
        run: echo '${{ inputs.release_notes }}' > release-notes.md
      - name: Convert Markdown to plain text with Pandoc
        uses: docker://pandoc/core:3.8
        with:
          args: "-f gfm -t plain --wrap=none release-notes.md -o release-notes.txt"
      - name: Install Firebase CLI (standalone)
        run: curl -sL https://firebase.tools | bash
      - name: Write Firebase service account
        run: echo '${{ secrets.firebase-credential-file-content }}' > "$RUNNER_TEMP/firebase-sa.json"
      - name: Distribute to Firebase App Distribution (CLI)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-sa.json
        run: |
          firebase appdistribution:distribute ${{ inputs.artifact_path }} \
            --app "${{ secrets.firebase-app-id }}" \
            --testers "kevinah95@gmail.com" \
            --release-notes-file release-notes.txt
